version: "3"
services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins-1
    ports:
      - 18181:8080
      - 50000:50000
    volumes:
      - ./jenkins:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djava.util.logging.config.file=/var/jenkins_home/log.properties
    networks:
      - my-devops
  gogs:
    image: gogs/gogs:latest
    container_name: gogs-1
    ports:
      - 10880:3000
      - 10022:22
    volumes:
      - ./gogs:/data
    networks:
      - my-devops
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql8-1
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=gogs
      - MYSQL_USER=gogs
      - MYSQL_PASSWORD=123456
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
    networks:
      - my-devops
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="1" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    

networks:
  my-devops:
    
      